server:
  port: 9530

spring:
  application:
    name: api-gateway

zuul:
  routes:
    hi:
      path: /api-hi/**
      serviceId: service-hi
    hi2:
      path: /api-hi2/**
      serviceId: service-hi2

eureka:
#客户端
  client:
#注册中心地址
    service-url:
      defaultZone: http://localhost:9527/eureka/